[package]
name = "snake-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
# rocket = { version = "0.5.1", features = ["secrets", "json"] }
rand = "0.9.1"
chrono = "0.4.41"
termion = "4.0.5"
macroquad = "0.4.14"
macroquad-tiled = "0.2.1"
macroquad-platformer = "0.2.0"
terminal_size = "0.4.2"
